name: country_data_picker
description: "A new Flutter plugin project."
version: 0.0.1
repository: 'https://github.com/Vitaly-V/country_data_picker'

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/flags/